version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-kpidb}
    volumes:
      - db-data:/var/lib/postgresql/data
    profiles: ["dev", "prod"]

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-kpidb}
    depends_on:
      - db
    profiles: ["dev", "prod"]

  frontend:
    build: ./frontend
    depends_on:
      - backend
    profiles: ["dev", "prod"]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    profiles: ["dev"]

  caddy:
    image: caddy:alpine
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    profiles: ["dev", "prod"]

volumes:
  db-data:
  caddy-data:
