name: Post Cycle Report
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip install requests
      - name: Run post-cycle report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_LOG_ISSUE: ${{ secrets.RUN_LOG_ISSUE }}
        run: python scripts/post_cycle_report.py
